# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: FloatingShuYin
subtitle:
description: 21世纪两大浪漫，五线谱与二进制。
keywords: FloatingShuYin
author: FloatingShuYin
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://floatsyi.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 'README.md'

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:FloatingShuYin/FloatingShuYin.GitHub.io.git
  branch: master

# feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '

# local search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# hot reload
browsersync:
  logLevel: "warn"
  ghostMode:
    scroll: true
  instanceName: "uniqueString"

# theme config
theme_config:
  # Sidebar Avatar
  avatar:
    # In theme directory (source/images): /images/avatar.gif
    # In site directory (source/uploads): /uploads/avatar.gif
    # You can also use other linking images.
    url: /images/avatar.png
    # If true, the avatar would be dispalyed in circle.
    rounded: true
    # If true, the avatar would be rotated with the cursor.
    rotated: true

  # ---------------------------------------------------------------
  # Menu Settings
  # ---------------------------------------------------------------

  # When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash from link value (/archives -> archives).
  # Usage: `Key: /link/ || icon`
  # Key is the name of menu item. If the translation for this item is available, the translated text will be loaded, otherwise the Key name will be used. Key is case-senstive.
  # Value before `||` delimeter is the target link.
  # Value after `||` delimeter is the name of FontAwesome icon. If icon (with or without delimeter) is not specified, question icon will be loaded.
  # External url should start with http:// or https://
  menu:
    home: / || home
    about: /about/ || user
    tags: /tags/ || tags
    categories: /categories/ || th
    archives: /archives/ || archive
    #schedule: /schedule/ || calendar
    #sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat

  # Enable / Disable menu icons / item badges.
  menu_settings:
    icons: true
    badges: false


  # ---------------------------------------------------------------
  # Scheme Settings
  # ---------------------------------------------------------------

  # Schemes
  scheme: Gemini
  #scheme: Muse
  #scheme: Mist
  #scheme: Pisces
  #scheme: Gemini


  # ---------------------------------------------------------------
  # Sidebar Settings
  # See: https://theme-next.org/docs/theme-settings/sidebar
  # ---------------------------------------------------------------

  # Posts / Categories / Tags in sidebar.
  site_state: true

  # Social Links
  # Usage: `Key: permalink || icon`
  # Key is the link label showing to end users.
  # Value before `||` delimeter is the target permalink.
  # Value after `||` delimeter is the name of FontAwesome icon. If icon (with or without delimeter) is not specified, globe icon will be loaded.
  social:
    GitHub: https://github.com/FloatingShuYin || github
    CodePen: https://codepen.io/FloatingShuYin/# || codepen
    #GitHub: https://github.com/yourname || github
    #E-Mail: mailto:yourname@gmail.com || envelope
    #Weibo: https://weibo.com/yourname || weibo
    #Google: https://plus.google.com/yourname || google
    #Twitter: https://twitter.com/yourname || twitter
    #FB Page: https://www.facebook.com/yourname || facebook
    #VK Group: https://vk.com/yourname || vk
    #StackOverflow: https://stackoverflow.com/yourname || stack-overflow
    #YouTube: https://youtube.com/yourname || youtube
    #Instagram: https://instagram.com/yourname || instagram
    #Skype: skype:yourname?call|chat || skype

  social_icons:
    enable: true
    icons_only: false
    transition: false

  # Local search
  # Dependencies: https://github.com/theme-next/hexo-generator-searchdb
  local_search:
    enable: true
    # If auto, trigger search by changing input.
    # If manual, trigger search by pressing enter key or search button.
    trigger: auto
    # Show top n results per article, show all results by setting to -1
    top_n_per_article: 1
    # Unescape html strings to the readable one.
    unescape: false

  # Show number of visitors to each article.
  # You can visit https://leancloud.cn to get AppID and AppKey.
  leancloud_visitors:
    enable: true
    app_id: bH5pXa93c9rYkIe6zzKkty1d-gzGzoHsz #<app_id>
    app_key: REvpf8v4c6CK9EgLRpFomYuL #<app_key>
    # Dependencies: https://github.com/theme-next/hexo-leancloud-counter-security
    # If you don't care about security in leancloud counter and just want to use it directly
    # (without hexo-leancloud-counter-security plugin), set `security` to `false`.
    security: false
    betterPerformance: false

  # Disqus
  disqus:
    enable: true
    shortname: FloatShuYin
    count: true
    lazyload: false

  # ---------------------------------------------------------------
  # Font Settings. Introduced in NexT v5.0.1.
  # Find fonts on Google Fonts (https://www.google.com/fonts)
  # All fonts set here will have the following styles:
  #   light, light italic, normal, normal italic, bold, bold italic
  # Be aware that setting too much fonts will cause site running slowly
  # ---------------------------------------------------------------
  # To avoid space between header and sidebar in scheme Pisces / Gemini, Web Safe fonts are recommended for `global` (and `logo`):
  # Arial | Tahoma | Helvetica | Times New Roman | Courier New | Verdana | Georgia | Palatino | Garamond | Comic Sans MS | Trebuchet MS
  # ---------------------------------------------------------------

  font:
    enable: true

    # Uri of fonts host, e.g. //fonts.googleapis.com (Default).
    host: //fonts.loli.net

    # Font options:
    # `external: true` will load this font family from `host` above.
    # `family: Times New Roman`. Without any quotes.
    # `size: xx`. Use `px` as unit.

    # Global font settings used for all elements in <body>.
    global:
      external: true
      family: Roboto Mono
      size:

    # Font settings for Headlines (H1, H2, H3, H4, H5, H6).
    # Fallback to `global` font settings.
    headings:
      external: true
      family: Roboto Mono
      size:

    # Font settings for posts.
    # Fallback to `global` font settings.
    posts:
      external: true
      family: Roboto Mono

    # Font settings for Logo.
    # Fallback to `global` font settings.
    logo:
      external: true
      family: Roboto Mono
      size:

    # Font settings for <code> and code blocks.
    codes:
      external: true
      family: Roboto Mono
      size:
  # Code Highlight
  codeblock:
    # Code Highlight theme
    # Available values: normal | night | night eighties | night blue | night bright | solarized | solarized dark | galactic
    # See: https://github.com/chriskempson/tomorrow-theme
    highlight_theme: tomorrow
    # Add copy button on codeblock
    copy_button:
      enable: true
      # Show text copy result.
      show_result: true
      # Available values: default | flat | mac
      style: mac
